### PR TITLE
Support building package for fedora40 on qt6

### PR DESCRIPTION
**Pull request by ovv**
I'm not very familiar with cmake, but this seems to do the trick to get a working RPM for fedora 40

### CODE REVIEW

**Comment by alex1701c** [comment]
I have updated the readme meanwhile. Could you please resolve the conflict?

**Comment by ovv** [comment]
> I have updated the readme meanwhile. Could you please resolve the conflict?

done

**Review by alex1701c — APPROVED** [review]

**Comment by alex1701c** [comment]
Thanks!

**Comment by alex1701c** [comment]
I have now added a more automated approach for generating those images. That work for qt5 and qt6 :)

**Pull request merged**
